# Generated by Django 5.2.6 on 2025-09-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="用例名称")),
                (
                    "case",
                    models.FileField(
                        upload_to="tests/%Y_%m_%d_%H_%M_%S/", verbose_name="用例文件"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "未执行"),
                            (1, "正在执行用例"),
                            (2, "正在生成报告"),
                            (3, "执行完毕"),
                        ],
                        verbose_name="测试状态",
                    ),
                ),
            ],
        ),
    ]
