# Generated by Django 5.2.6 on 2025-09-28 20:33

import Sj_app2.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("9dcdab52-485f-44d5-a042-07bdacf7d1fa"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="任务名称")),
                (
                    "case",
                    models.FileField(
                        upload_to=Sj_app2.models.get_case_path, verbose_name="用例文件"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (-2, "出现错误"),
                            (-1, "初始化"),
                            (0, "等待执行"),
                            (1, "执行用例"),
                            (2, "生成报告"),
                            (3, "执行完毕"),
                        ],
                        default=-1,
                        verbose_name="测试状态",
                    ),
                ),
                (
                    "is_processing",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="正在执行"
                    ),
                ),
                (
                    "is_pass",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="是否通过"
                    ),
                ),
                (
                    "has_report",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="拥有报告"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updaate_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新"),
                ),
            ],
            options={
                "verbose_name": "测试任务",
                "verbose_name_plural": "测试任务",
            },
        ),
    ]
