# Generated by Django 5.2.6 on 2025-09-28 21:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sj_app2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testtask",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("eff28cd4-cb1f-4f11-ad6c-84ff96ed5033"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
