# Generated by Django 5.2.6 on 2025-09-28 21:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sj_app2", "0002_alter_testtask_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testtask",
            old_name="updaate_time",
            new_name="update_time",
        ),
        migrations.AlterField(
            model_name="testtask",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("dc365cd7-4aeb-43d9-b1d5-81a068d2b158"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
