# Generated by Django 5.2.6 on 2025-09-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quality", models.IntegerField(default=1, verbose_name="商品质量")),
                ("attitude", models.IntegerField(default=1, verbose_name="客服态度")),
                ("speed", models.IntegerField(default=1, verbose_name="物流速度")),
                (
                    "comment",
                    models.TextField(
                        blank=True, max_length=260, verbose_name="评价内容"
                    ),
                ),
                (
                    "anonymous",
                    models.BooleanField(default=False, verbose_name="是否匿名"),
                ),
            ],
        ),
    ]
