# Generated by Django 5.2.6 on 2025-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sj_app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="comment",
            field=models.TextField(
                blank=True, default="", max_length=260, verbose_name="评价内容"
            ),
        ),
    ]
